config/routes.rb
Rails.application.routes.draw do
  
  resources :plans
  resources :spots
  root "plans#index"
  devise_for :users
  post "/plans/:id/edit" => "plan_spots#create"
  delete "/plans" => "plan_spots#destroy", as: "delete_plan_spot"
  get "plan_spot/new/:plan_id" => "plan_spots#new", as: "new_plan_spots"
  post "plan_spot/new/:plan_id" => "plan_spots#create", as: "create_plan_spots"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plan.rb
class Plan < ApplicationRecord
    has_many :plan_spots, dependent: :destroy
    has_many :spots, through: :plan_spots
  
end

app/models/plan_spot.rb
class PlanSpot < ApplicationRecord
  belongs_to :plan
  belongs_to :spot
end

app/models/spot.rb
class Spot < ApplicationRecord
    has_many :plan_spots, dependent: :destroy
    has_many :plans, through: :plan_spots
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plan_spots_controller.rb
class PlanSpotsController < ApplicationController
    before_action :authenticate_user!

    def new
        @plan = Plan.find(params[:plan_id])
        if params[:search].present?
            @spots = Spot.where(['name LIKE ? OR address LIKE ? OR body LIKE ?', '%' + params[:search] + '%', '%' + params[:search] + '%', '%' + params[:search] + '%'])
          else
            @spots = Spot.all
          end
        @plan_spot = PlanSpot.new
    end
    

    def create 
        @plan_spot = PlanSpot.new(plan_spot_params)
        if @plan_spot.save
            redirect_to edit_plan_path(@plan_spot.plan_id)
        else
            redirect_back(fallback_location: root_path)
        end
    end

    def destroy 
        @plan_spot = PlanSpot.find_by(plan_id: params[:plan_id], spot_id: params[:spot_id])
        @plan_spot.destroy 
        redirect_back(fallback_location: root_path)
    end

    private
    def plan_spot_params
        params.permit(:plan_id,:spot_id)
    end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /plans
  # GET /plans.json
  def index
    if params[:search].present?
      @plans = Plan.where(['name LIKE ? OR dscr LIKE ?', '%' + params[:search] + '%', '%' + params[:search] + '%'])
    else
      @plans = Plan.all
    end
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
    @plan_spots = PlanSpot.new
    @spots = @plan.spots
    
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plan_params
      params.require(:plan).permit(:name, :dscr)
    end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :set_spot, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /spots
  # GET /spots.json
  def index
    if params[:search].present?
      @spots = Spot.where(['name LIKE ? OR address LIKE ? OR body LIKE ?', '%' + params[:search] + '%', '%' + params[:search] + '%', '%' + params[:search] + '%'])
    else
      @spots = Spot.all
    end
  end

  # GET /spots/1
  # GET /spots/1.json
  def show
  end

  # GET /spots/new
  def new
    @spot = Spot.new
  end

  # GET /spots/1/edit
  def edit
  end

  # POST /spots
  # POST /spots.json
  def create
    @spot = Spot.new(spot_params)

    respond_to do |format|
      if @spot.save
        format.html { redirect_to @spot, notice: 'Spot was successfully created.' }
        format.json { render :show, status: :created, location: @spot }
      else
        format.html { render :new }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spots/1
  # PATCH/PUT /spots/1.json
  def update
    respond_to do |format|
      if @spot.update(spot_params)
        format.html { redirect_to @spot, notice: 'Spot was successfully updated.' }
        format.json { render :show, status: :ok, location: @spot }
      else
        format.html { render :edit }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spots/1
  # DELETE /spots/1.json
  def destroy
    @spot.destroy
    respond_to do |format|
      format.html { redirect_to spots_url, notice: 'Spot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spot
      @spot = Spot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def spot_params
      params.require(:spot).permit(:name, :address, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plan_spots_helper.rb
module PlanSpotsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oinsta</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plan_spots/new.html.erb
<h1>Add Spot To <%= @plan.name%></h1>
<h3>Search</h3>
 <%= form_tag({controller:"plan_spots",action:"new",plan_id:@plan.id}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag 'search'  %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spots.each do |spot| %>
      <tr>
        <td><%= spot.name %></td>
        <td><%= spot.address %></td>
        <td><%= spot.body %></td>
        <td><%= link_to 'Show', spot %></td>
        <td>
            <%= form_with(model: @plan_sopt, local: true) do |form| %>

                <div class="field">
                    <%= form.hidden_field :plan_id, value: @plan.id%>
                </div>

                <div class="field">
                    <%= form.hidden_field :spot_id, value: spot.id%>
                </div>

                <div class="actions">
                    <%= form.submit "Add" %>
                </div>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/plans/_form.html.erb
<%= form_with(model: plan, local: true) do |form| %>
  <% if plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
        <% plan.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :dscr %>
    <%= form.text_area :dscr %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing Plan</h1>

Added Spot<br>
<% @spots.each do |s| %>
    name:
    <%= s.name%>|
    address:
    <%= s.address%>|
    body:
    <%= s.body%>|
    <%= button_to 'Destroy',delete_plan_spot_path(:plan_id =>params[:id], :spot_id => s.id), method: :delete, data: { confirm: 'Are you sure?' } %>
    <br>
<% end %>

<h3><%= link_to "Add Spot" ,new_plan_spots_path(:plan_id => @plan.id) %></h3>


<%= render 'form', plan: @plan %>

<%= link_to 'Show', @plan %> |
<%= link_to "Back", :back %>

app/views/plans/index.html.erb
<h1>Plans</h1>

<p id="notice"><%= notice %></p>

<h3>Search</h3>
 <%= form_tag({controller:"plans",action:"index"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag 'search'  %>
<% end %>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dscr</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.name %></td>
        <td><%= plan.dscr %></td>
        <td><%= link_to 'Show', plan %></td>
        <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
        <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plan', new_plan_path %>
<%= link_to 'New Spot', new_spot_path %>
<%= link_to 'Spot Index', spots_path %>

app/views/plans/new.html.erb
<h1>New Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'create spot', new_spot_path %>
<%= link_to "Back", :back %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plan.name %>
</p>

<p>
  <strong>Dscr:</strong>
  <%= @plan.dscr %>
</p>
<strong>Spots</strong><br>
<% @plan.spots.each do |s| %>
    name:
    <%= s.name%>|
    address:
    <%= s.address%>|
    body:
    <%= s.body%>|
    <%= link_to 'show', spot_path(s.id) %>
    <br>
<% end %>

<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>

app/views/spots/_form.html.erb
<%= form_with(model: spot, local: true) do |form| %>
  <% if spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spot.errors.count, "error") %> prohibited this spot from being saved:</h2>

      <ul>
        <% spot.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/spots/edit.html.erb
<h1>Editing Spot</h1>

<%= render 'form', spot: @spot %>

<%= link_to 'Show', @spot %> |
<%= link_to 'Back', spots_path %>

app/views/spots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Spots</h1>

<h3>Search</h3>
 <%= form_tag({controller:"spots",action:"index"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag 'search'  %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spots.each do |spot| %>
      <tr>
        <td><%= spot.name %></td>
        <td><%= spot.address %></td>
        <td><%= spot.body %></td>
        <td><%= link_to 'Show', spot %></td>
        <td><%= link_to 'Edit', edit_spot_path(spot) %></td>
        <td><%= link_to 'Destroy', spot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Spot', new_spot_path %>
<%= link_to 'New plan', new_plan_path %>
<%= link_to 'Plan index', plans_path %>

app/views/spots/new.html.erb
<h1>New Spot</h1>

<%= render 'form', spot: @spot %>

<%= link_to "Back", :back %>

app/views/spots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @spot.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @spot.address %>
</p>

<p>
  <strong>Body:</strong>
  <%= @spot.body %>
</p>

<%= link_to 'Edit', edit_spot_path(@spot) %> |
<%= link_to "Back", :back %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>